import type { Product, Category } from '../types/product.types'

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Bebidas', slug: 'bebidas' },
  { id: 'cat-2', name: 'Alimentos', slug: 'alimentos' },
  { id: 'cat-3', name: 'Cuidado Personal', slug: 'cuidado-personal' },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Café Orgánico Tarrazú',
    description: 'Café de altura cultivado en la zona de Los Santos, Tarrazú. 100% orgánico y de comercio justo.',
    price: 5500,
    categoryId: 'cat-1',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400',
    stock: 50,
    isOrganic: true,
    isFeatured: true,
    slug: 'cafe-organico-tarrazu',
    presentation: '350 GR',
  },
  {
    id: 'prod-2',
    name: 'Miel de Abejas Silvestres',
    description: 'Miel pura recolectada de colmenas nativas del bosque costarricense.',
    price: 3200,
    categoryId: 'cat-2',
    imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400',
    stock: 30,
    isOrganic: true,
    isFeatured: true,
    slug: 'miel-abejas-silvestres',
    presentation: '500 GR',
  },
  {
    id: 'prod-3',
    name: 'Aceite de Coco Prensado en Frío',
    description: 'Aceite de coco virgen extra, prensado en frío, ideal para cocinar y cuidado de la piel.',
    price: 4800,
    categoryId: 'cat-2',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    stock: 25,
    isOrganic: true,
    isFeatured: false,
    slug: 'aceite-coco-prensado-frio',
    presentation: '500 ML',
  },
  {
    id: 'prod-4',
    name: 'Jabón Artesanal de Aloe Vera',
    description: 'Jabón natural elaborado con aloe vera y aceites esenciales, sin químicos artificiales.',
    price: 1800,
    categoryId: 'cat-3',
    imageUrl: 'https://images.unsplash.com/photo-1600857062241-98e5dba7f33c?w=400',
    stock: 100,
    isOrganic: true,
    isFeatured: false,
    slug: 'jabon-artesanal-aloe-vera',
    presentation: '100 GR',
  },
  {
    id: 'prod-5',
    name: 'Granola Artesanal Tropical',
    description: 'Granola con avena integral, coco, maracuyá y guanábana deshidratada.',
    price: 2900,
    categoryId: 'cat-2',
    imageUrl: 'https://images.unsplash.com/photo-1517093157656-b9eccef91cb1?w=400',
    stock: 40,
    isOrganic: true,
    isFeatured: true,
    slug: 'granola-artesanal-tropical',
    presentation: '400 GR',
  },
  {
    id: 'prod-6',
    name: 'Té de Hierba Limón',
    description: 'Hierba limón seca de cultivo orgánico. Perfecta para infusiones relajantes.',
    price: 1500,
    categoryId: 'cat-1',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400',
    stock: 60,
    isOrganic: true,
    isFeatured: false,
    slug: 'te-hierba-limon',
    presentation: '20 BOLSITAS',
  },
]
