-- Create categories table
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL UNIQUE,
  slug VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create products table
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  presentation VARCHAR(100),
  category_id UUID NOT NULL REFERENCES categories(id),
  image_url TEXT,
  stock INTEGER NOT NULL DEFAULT 0,
  is_organic BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  slug VARCHAR(255) UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_slug ON products(slug);
CREATE INDEX idx_products_is_organic ON products(is_organic);

-- Insert categories
INSERT INTO categories (name, slug) VALUES
  ('Carnes Libre Hormonas/Antib', 'carnes-libre-hormonas-antib'),
  ('Convencional', 'convencional'),
  ('Hidroponico', 'hidroponico'),
  ('Huevo', 'huevo'),
  ('Libre Pesticidas', 'libre-pesticidas'),
  ('Mini Vegetal', 'mini-vegetal'),
  ('Organico', 'organico');

-- Insert products
DO $$
DECLARE
  cat_carnes UUID;
  cat_conv UUID;
  cat_hidro UUID;
  cat_huevo UUID;
  cat_libre UUID;
  cat_mini UUID;
  cat_org UUID;
BEGIN
  SELECT id INTO cat_carnes FROM categories WHERE slug = 'carnes-libre-hormonas-antib';
  SELECT id INTO cat_conv FROM categories WHERE slug = 'convencional';
  SELECT id INTO cat_hidro FROM categories WHERE slug = 'hidroponico';
  SELECT id INTO cat_huevo FROM categories WHERE slug = 'huevo';
  SELECT id INTO cat_libre FROM categories WHERE slug = 'libre-pesticidas';
  SELECT id INTO cat_mini FROM categories WHERE slug = 'mini-vegetal';
  SELECT id INTO cat_org FROM categories WHERE slug = 'organico';

  INSERT INTO products (name, price, presentation, category_id, stock, is_organic, slug) VALUES
    ('Mano de Piedra Res', 11270, 'KG', cat_carnes, 0, false, 'mano-de-piedra-res'),
    ('Ala Pollo Pastoreo', 4059, 'KG', cat_carnes, 0, false, 'ala-pollo-pastoreo'),
    ('Chorizo Especial', 7140, 'KG', cat_carnes, 0, false, 'chorizo-especial'),
    ('Chuleta de Cerdo Pastores', 7037, 'KG', cat_carnes, 0, false, 'chuleta-cerdo-pastores'),
    ('Churrasco Premium', 16106, 'KG', cat_carnes, 0, false, 'churrasco-premium'),
    ('Costilla Baby Back Pastoreo', 8500, 'KG', cat_carnes, 0, false, 'costilla-baby-back-pastoreo'),
    ('Costilla de Res Premium', 6832, 'KG', cat_carnes, 0, false, 'costilla-res-premium'),
    ('Costilla Parrillera', 7200, 'KG', cat_carnes, 0, false, 'costilla-parrillera'),
    ('Costilla San Luis Cerdo Past', 8485, 'KG', cat_carnes, 0, false, 'costilla-san-luis-cerdo-past'),
    ('Filet Mignon Premium', 21239, 'KG', cat_carnes, 0, false, 'filet-mignon-premium'),
    ('Lomito Res Premium', 19092, 'KG', cat_carnes, 0, false, 'lomito-res-premium'),
    ('Lomo Ancho Premium', 16102, 'KG', cat_carnes, 0, false, 'lomo-ancho-premium'),
    ('Lomo Ancho Res', 15929, 'KG', cat_carnes, 0, false, 'lomo-ancho-res'),
    ('Lomo de Aguja', 10699, 'KG', cat_carnes, 0, false, 'lomo-de-aguja'),
    ('Lomo de Cerdo Pastoreo', 8100, 'KG', cat_carnes, 0, false, 'lomo-cerdo-pastoreo'),
    ('Molida Especial 5% Grasa', 8719, 'KG', cat_carnes, 0, false, 'molida-especial-5-grasa'),
    ('Muslo Pollo Desh', 5220, 'KG', cat_carnes, 0, false, 'muslo-pollo-desh'),
    ('Muslo Pollo Pastoreo', 3000, 'KG', cat_carnes, 0, false, 'muslo-pollo-pastoreo'),
    ('New York Steak Premium', 16097, 'KG', cat_carnes, 0, false, 'new-york-steak-premium'),
    ('Pechuga Deshuesada', 6550, 'KG', cat_carnes, 0, false, 'pechuga-deshuesada'),
    ('Pechuga Pollo Pastoreo', 4305, 'KG', cat_carnes, 0, false, 'pechuga-pollo-pastoreo'),
    ('Pollo Entero Pastoreo', 7807, 'UNID', cat_carnes, 0, false, 'pollo-entero-pastoreo'),
    ('Posta de Cerdo', 4340, 'KG', cat_carnes, 0, false, 'posta-cerdo'),
    ('Posta Quititeña', 8478, 'KG', cat_carnes, 0, false, 'posta-quititena'),
    ('Punta de Solomo', 11181, 'KG', cat_carnes, 0, false, 'punta-solomo'),
    ('Rabo Res', 7119, 'KG', cat_carnes, 0, false, 'rabo-res'),
    ('Rib Eye Premium', 16097, 'KG', cat_carnes, 0, false, 'rib-eye-premium'),
    ('Sirloin Premium', 12535, 'KG', cat_carnes, 0, false, 'sirloin-premium'),
    ('T-Bone Premium', 17823, 'KG', cat_carnes, 0, false, 't-bone-premium'),
    ('Trociro de Res Premium', 8400, 'KG', cat_carnes, 0, false, 'trociro-res-premium'),
    ('Vuelta de Lomo Premium', 9646, 'KG', cat_carnes, 0, false, 'vuelta-lomo-premium'),
    ('Aguacate Hass', 1020, 'UNID', cat_conv, 0, false, 'aguacate-hass'),
    ('Ajo', 1980, 'KG', cat_conv, 0, false, 'ajo'),
    ('Ajo Criollo', 15500, 'KG', cat_conv, 0, false, 'ajo-criollo'),
    ('Ajo Criollo 250 Gr', 4050, '250 GR', cat_conv, 0, false, 'ajo-criollo-250-gr'),
    ('Alfalfa', 1500, 'BANDEJA', cat_conv, 0, false, 'alfalfa'),
    ('Arandano', 2790, 'BANDEJA 125 GR', cat_conv, 0, false, 'arandano'),
    ('Ayote Mantequilla', 2250, 'UNID', cat_conv, 0, false, 'ayote-mantequilla'),
    ('Ayote Sazon', 2317, 'UNID', cat_conv, 0, false, 'ayote-sazon'),
    ('Ayote Tierno', 903, 'UNID', cat_conv, 0, false, 'ayote-tierno'),
    ('Banano', 80, 'UNID', cat_conv, 0, false, 'banano'),
    ('Banano Criollo', 84, 'UNID', cat_conv, 0, false, 'banano-criollo'),
    ('Berenjena', 832, 'UNID', cat_conv, 0, false, 'berenjena'),
    ('Berro', 801, 'ROLLO', cat_conv, 0, false, 'berro'),
    ('Brocoli', 1850, 'UNID', cat_conv, 0, false, 'brocoli'),
    ('Camote', 1360, 'KG', cat_conv, 0, false, 'camote'),
    ('Carambola', 1500, 'KG', cat_conv, 0, false, 'carambola'),
    ('Cas', 1265, 'KG', cat_conv, 0, false, 'cas'),
    ('Cebolla', 1400, 'KG', cat_conv, 0, false, 'cebolla'),
    ('Cebolla Morada', 2500, 'KG', cat_conv, 0, false, 'cebolla-morada'),
    ('Chayote', 450, 'UNID', cat_conv, 0, false, 'chayote'),
    ('Chayote Negro', 525, 'UNID', cat_conv, 0, false, 'chayote-negro'),
    ('Chile Jalapeno', 2880, 'KG', cat_conv, 0, false, 'chile-jalapeno'),
    ('Chile Panameno', 2880, 'KG', cat_conv, 0, false, 'chile-panameno'),
    ('Cocos', 720, 'UNID', cat_conv, 0, false, 'cocos'),
    ('Coliflor', 1200, 'UNID', cat_conv, 0, false, 'coliflor'),
    ('Culantro de Coyote', 248, 'ROLLO', cat_conv, 0, false, 'culantro-coyote'),
    ('Curcuma', 2699, 'KG', cat_conv, 0, false, 'curcuma'),
    ('Elote Dulce', 2650, 'BANDEJA', cat_conv, 0, false, 'elote-dulce'),
    ('Frijol Nacido', 1261, 'BANDEJA', cat_conv, 0, false, 'frijol-nacido'),
    ('Frijol Tierno', 2164, 'BANDEJA', cat_conv, 0, false, 'frijol-tierno'),
    ('Granadilla', 327, 'UNID', cat_conv, 0, false, 'granadilla'),
    ('Guanabana', 6372, 'UNID', cat_conv, 0, false, 'guanabana'),
    ('Guayaba', 721, 'UNID', cat_conv, 0, false, 'guayaba'),
    ('Guayaba Nacional', 1770, 'UNID', cat_conv, 0, false, 'guayaba-nacional'),
    ('Guineo', 54, 'UNID', cat_conv, 0, false, 'guineo'),
    ('Hinojo', 920, 'ROLLO', cat_conv, 0, false, 'hinojo'),
    ('Hongos Blancos', 2991, 'BANDEJA', cat_conv, 0, false, 'hongos-blancos'),
    ('Hongos Crimini', 4491, 'BANDEJA', cat_conv, 0, false, 'hongos-crimini'),
    ('Hongo Ostra', 4500, 'BANDEJA', cat_conv, 0, false, 'hongo-ostra'),
    ('Hongo Portobelo', 4513, 'BANDEJA', cat_conv, 0, false, 'hongo-portobelo'),
    ('Jengibre', 2699, 'KG', cat_conv, 0, false, 'jengibre'),
    ('Kale Morado', 845, 'ROLLO', cat_conv, 0, false, 'kale-morado'),
    ('Kiwi', 642, 'UNID', cat_conv, 0, false, 'kiwi'),
    ('Limon Dulce', 360, 'UNID', cat_conv, 0, false, 'limon-dulce'),
    ('Limon Mandarina', 300, 'UNID', cat_conv, 0, false, 'limon-mandarina'),
    ('Limon Mesino', 360, 'UNID', cat_conv, 0, false, 'limon-mesino'),
    ('Mandarina', 363, 'UNID', cat_conv, 0, false, 'mandarina'),
    ('Mandarina Importada', 540, 'UNID', cat_conv, 0, false, 'mandarina-importada'),
    ('Mango Maduro', 1649, 'KG', cat_conv, 0, false, 'mango-maduro'),
    ('Manzana Amarilla', 558, 'UNID', cat_conv, 0, false, 'manzana-amarilla'),
    ('Manzana Gala', 739, 'UNID', cat_conv, 0, false, 'manzana-gala'),
    ('Manzana Roja', 739, 'UNID', cat_conv, 0, false, 'manzana-roja'),
    ('Manzana Verde', 743, 'UNID', cat_conv, 0, false, 'manzana-verde'),
    ('Maracuya', 2040, 'KG', cat_conv, 0, false, 'maracuya'),
    ('Melocoton', 720, 'UNID', cat_conv, 0, false, 'melocoton'),
    ('Melon', 2163, 'UNID', cat_conv, 0, false, 'melon'),
    ('Mora', 3703, 'KG', cat_conv, 0, false, 'mora'),
    ('Nabo', 1947, 'UNID', cat_conv, 0, false, 'nabo'),
    ('Name', 1280, 'KG', cat_conv, 0, false, 'name'),
    ('Nampi', 2160, 'KG', cat_conv, 0, false, 'nampi'),
    ('Naranja', 129, 'UNID', cat_conv, 0, false, 'naranja'),
    ('Naranjas', 181, 'UND', cat_conv, 0, false, 'naranjas'),
    ('Packchoi', 1050, 'ROLLO', cat_conv, 0, false, 'packchoi'),
    ('Papa Amarilla', 700, 'KG', cat_conv, 0, false, 'papa-amarilla'),
    ('Papa Mini', 1350, 'KG', cat_conv, 0, false, 'papa-mini'),
    ('Papaya', 1900, 'UNID', cat_conv, 0, false, 'papaya'),
    ('Pejivalle', 1668, 'KG', cat_conv, 0, false, 'pejivalle'),
    ('Pepino', 400, 'KG', cat_conv, 0, false, 'pepino'),
    ('Pera', 655, 'UNID', cat_conv, 0, false, 'pera'),
    ('Pina', 1668, 'UNID', cat_conv, 0, false, 'pina'),
    ('Platano Maduro', 406, 'UNID', cat_conv, 0, false, 'platano-maduro'),
    ('Platano Verde', 406, 'UNID', cat_conv, 0, false, 'platano-verde'),
    ('Radicchio', 1500, 'ROLLO', cat_conv, 0, false, 'radicchio'),
    ('Sandia', 2703, 'UNID', cat_conv, 0, false, 'sandia'),
    ('Tamarindo', 350, 'PELOTA', cat_conv, 0, false, 'tamarindo'),
    ('Tiquisque', 2520, 'KG', cat_conv, 0, false, 'tiquisque'),
    ('Toronja', 1360, 'UNID', cat_conv, 0, false, 'toronja'),
    ('Uva Globo', 4504, 'KG', cat_conv, 0, false, 'uva-globo'),
    ('Uva Negra', 7522, 'KG', cat_conv, 0, false, 'uva-negra'),
    ('Uva Roja', 4336, 'KG', cat_conv, 0, false, 'uva-roja'),
    ('Uva Verde', 8102, 'KG', cat_conv, 0, false, 'uva-verde'),
    ('Vainica', 1300, 'KG', cat_conv, 0, false, 'vainica'),
    ('Yuca Parafinada', 837, 'KG', cat_conv, 0, false, 'yuca-parafinada'),
    ('Zapallo', 1200, 'UNID', cat_conv, 0, false, 'zapallo'),
    ('Zuchinni', 1200, 'UNID', cat_conv, 0, false, 'zuchinni'),
    ('Zuquini', 991, 'UNID', cat_conv, 0, false, 'zuquini'),
    ('Mix de Berries', 2000, 'CAJITA', cat_hidro, 0, false, 'mix-berries'),
    ('Cebolla Mini Hidroponica', 1279, 'ROLLO', cat_hidro, 0, false, 'cebolla-mini-hidroponica'),
    ('Cebolete Hidroponico', 841, 'ROLLO', cat_hidro, 0, false, 'cebolete-hidroponico'),
    ('Cebollete', 783, 'ROLLO', cat_hidro, 0, false, 'cebollete'),
    ('Mix Chile Mundial Hidroponico', 2960, 'PAQUETE', cat_hidro, 0, false, 'mix-chile-mundial-hidroponico'),
    ('Mora Libre de Pestic', 1851, 'CAJITA', cat_hidro, 0, false, 'mora-libre-pestic'),
    ('Tico Berrie Mix', 3142, 'CAJITA', cat_hidro, 0, false, 'tico-berrie-mix'),
    ('Tomate Cherry', 1589, 'BANDEJA', cat_hidro, 0, false, 'tomate-cherry'),
    ('Uchuva 250 Gr', 3146, 'BANDEJA', cat_hidro, 0, false, 'uchuva-250-gr'),
    ('Vainica Hidro', 1173, 'BANDEJA', cat_hidro, 0, false, 'vainica-hidro'),
    ('Huevo Past 30 Unid', 5782, '30 UNID', cat_huevo, 0, false, 'huevo-past-30-unid'),
    ('Huevo Pastoreo 12 Unid', 2381, '12 UNID', cat_huevo, 0, false, 'huevo-pastoreo-12-unid'),
    ('Albahaca', 540, 'ROLLO', cat_libre, 0, false, 'albahaca'),
    ('Eneldo', 814, 'ROLLO', cat_libre, 0, false, 'eneldo'),
    ('Estragon', 500, 'ROLLO', cat_libre, 0, false, 'estragon'),
    ('Hierba Buena', 500, 'ROLLO', cat_libre, 0, false, 'hierba-buena'),
    ('Menta', 500, 'ROLLO', cat_libre, 0, false, 'menta'),
    ('Oregano', 500, 'ROLLO', cat_libre, 0, false, 'oregano'),
    ('Perejil Italiano', 500, 'ROLLO', cat_libre, 0, false, 'perejil-italiano'),
    ('Chayote Mini', 593, 'BANDEJA', cat_mini, 0, false, 'chayote-mini'),
    ('Elote Mini', 2336, 'BANDEJA', cat_mini, 0, false, 'elote-mini'),
    ('Escalopin', 1704, 'BANDEJA', cat_mini, 0, false, 'escalopin'),
    ('Mix Minivegetales', 2336, 'BANDEJA', cat_mini, 0, false, 'mix-minivegetales'),
    ('Vainica Mini', 2336, 'BANDEJA', cat_mini, 0, false, 'vainica-mini'),
    ('Zuchinni Mini', 2336, 'BANDEJA', cat_mini, 0, false, 'zuchinni-mini'),
    ('Arroz Organico Regenerativo', 2800, 'KILO', cat_org, 0, true, 'arroz-organico-regenerativo'),
    ('Acelga de Colores', 655, 'ROLLO', cat_org, 0, true, 'acelga-colores'),
    ('Acelga Verde', 633, 'ROLLO', cat_org, 0, true, 'acelga-verde'),
    ('Rabanito', 468, 'ROLLO', cat_org, 0, true, 'rabanito'),
    ('Acelga Organica', 655, 'ROLLO', cat_org, 0, true, 'acelga-organica'),
    ('Apio Organico', 1180, '250 GR', cat_org, 0, true, 'apio-organico'),
    ('Arugula Organica', 845, 'ROLLO', cat_org, 0, true, 'arugula-organica'),
    ('Brocoli Organica', 1120, 'UNID', cat_org, 0, true, 'brocoli-organica'),
    ('Cafe Organico Rosa Blanca', 8614, '350 GR', cat_org, 0, true, 'cafe-organico-rosa-blanca'),
    ('Cebollin Organico', 955, 'ROLLO', cat_org, 0, true, 'cebollin-organico'),
    ('Chile Dulce Organico', 715, 'UNID', cat_org, 0, true, 'chile-dulce-organico'),
    ('Culantro Organico', 565, 'ROLLO', cat_org, 0, true, 'culantro-organico'),
    ('Espinaca Organica', 845, 'ROLLO', cat_org, 0, true, 'espinaca-organica'),
    ('Kale Organico', 845, 'ROLLO', cat_org, 0, true, 'kale-organico'),
    ('Lechuga Americana Organica', 755, 'UNID', cat_org, 0, true, 'lechuga-americana-organica'),
    ('Lechuga Freeze Organica', 755, 'UNID', cat_org, 0, true, 'lechuga-freeze-organica'),
    ('Lechuga Lolo Rosa Organica', 755, 'UNID', cat_org, 0, true, 'lechuga-lolo-rosa-organica'),
    ('Lechuga Romana', 755, 'UNID', cat_org, 0, true, 'lechuga-romana'),
    ('Oregano Organico', 840, 'ROLLO', cat_org, 0, true, 'oregano-organico'),
    ('Packchoi Organ', 1060, 'ROLLO', cat_org, 0, true, 'packchoi-organ'),
    ('Pepino Organico', 554, 'KG', cat_org, 0, true, 'pepino-organico'),
    ('Perejil Organico', 530, 'ROLLO', cat_org, 0, true, 'perejil-organico'),
    ('Pina Organica', 2980, 'UNID', cat_org, 0, true, 'pina-organica'),
    ('Puerro Organico', 930, 'ROLLO', cat_org, 0, true, 'puerro-organico'),
    ('Rabanito Organico', 760, 'ROLLO', cat_org, 0, true, 'rabanito-organico'),
    ('Remolacha Organica', 680, 'UNID', cat_org, 0, true, 'remolacha-organica'),
    ('Repollo Morado', 980, 'UNID', cat_org, 0, true, 'repollo-morado'),
    ('Repollo Morado Organico', 855, 'UNID', cat_org, 0, true, 'repollo-morado-organico'),
    ('Repollo Verde Organico', 820, 'UNID', cat_org, 0, true, 'repollo-verde-organico'),
    ('Romero Organico', 752, 'ROLLO', cat_org, 0, true, 'romero-organico'),
    ('Tomate Cherry Organico', 1900, 'BANDEJA', cat_org, 0, true, 'tomate-cherry-organico'),
    ('Tomillo Organico', 840, 'ROLLO', cat_org, 0, true, 'tomillo-organico'),
    ('Zanahoria Mini Organica', 2035, 'BANDEJA', cat_org, 0, true, 'zanahoria-mini-organica'),
    ('Zanahoria Organica', 1495, 'KG', cat_org, 0, true, 'zanahoria-organica');
END $$;
